### ISSUE TITLE
Search existing communities

### ISSUE THREAD

**Issue by juldebar** [eblondel/zen4R#1]
I faced an issue with Zen4R to find an existing community. Zen4R is able to locate the community in Zenodo but not in Zenodo Sandbox.

**Comment by eblondel** [comment]
I've checked and this is due to number of communities retrieved in the
service. To list all communities in one shot I had to set a number of pages
in the call to Zenodo, set to 1000, which is enough for the public Zenodo
but not in sandbox. I will set it to 10000. We may need later to set it a
multiple page requests if a single request becomes too heavy.

Le jeu. 11 avr. 2019 08:51, Julien Barde <notifications@github.com> a
écrit :

**Comment by eblondel** [comment]
Done can you check?
